### ISSUE TITLE
Impossible to delete a resource group

### ISSUE THREAD

**Issue by Harimzial** [LibreBooking/docker#82]
Hi @colisee 

Well, I have a very limited knowledge about coding, so I'll only be able to bug report. And here I am again. 

I have an issue with resource groups, i can create, rename and use them. But i cannot delete them.
Here is the error from the logs when i try to remove one (right click > delete, on the name) : 

```
2023-11-28T10:01:57.333945724Z 172.19.0.1 - - [28/Nov/2023:11:01:57 +0100] "GET /Web/scripts/js/jquery.contextMenu.js?v=2.8.6.1 HTTP/1.1" 200 13317 "https://URL/Web/admin/manage_resource_groups.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36"

2023-11-28T10:02:02.901820855Z [Tue Nov 28 11:02:02.901590 2023] [php:notice] [pid 81] [client 172.19.0.1:50608] Error: ValueError: The arguments array must contain 2 items, 1 given in /var/www/html/lib/Common/Logging/Log.php:77\nStack trace:\n#0 /var/www/html/lib/Common/Logging/Log.php(77): vsprintf()\n#1 /var/www/html/Presenters/Admin/ManageResourceGroupsPresenter.php(123): Log::Debug()\n#2 /var/www/html/Presenters/ActionPresenter.php(68): ManageResourceGroupsPresenter->DeleteGroup()\n#3 /var/www/html/Pages/Admin/ManageResourceGroupsPage.php(90): ActionPresenter->ProcessAction()\n#4 /var/www/html/Pages/ActionPage.php(27): ManageResourceGroupsPage->ProcessAction()\n#5 /var/www/html/Pages/SecurePage.php(54): ActionPage->PageLoad()\n#6 /var/www/html/Web/admin/manage_resource_groups.php(9): SecureActionPageDecorator->PageLoad()\n#7 {main}, referer: https://URL/Web/admin/manage_resource_groups.php

2023-11-28T10:02:02.901880179Z [Tue Nov 28 11:02:02.901623 2023] [php:notice] [pid 81] [client 172.19.0.1:50608] #0 /var/www/html/lib/Common/Logging/ExceptionHandler.php(22): WebExceptionHandler->HandleException(Object(ValueError))\n#1 [internal function]: ExceptionHandler::Handle(Object(ValueError))\n, referer: https://URL/Web/admin/manage_resource_groups.php

2023-11-28T10:02:02.918305404Z 172.19.0.1 - - [28/Nov/2023:11:02:02 +0100] "POST /Web/admin/manage_resource_groups.php?action=DeleteGroup&nid=1 HTTP/1.1" 200 2955 "https://URL/Web/admin/manage_resource_groups.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36"
```

Let me know if you have an idea :)
Have a good day!

**Comment by colisee** [comment]
Hi @Harimzial ,

I was able to reproduce the same issue as you with both image tags `2.8.6.1` and `develop`.

I will quickly check but I suspect this issue comes from upstream...

**Comment by colisee** [comment]
@Harimzial, 

I confirm it is a bug from [upstream](https://github.com/librebooking/app) and I will push a pull-request. 

Please bear in mind that this issue will be solved with a future image librebooking/librebooking:`develop` when the pull-request is accepted. 

If you have other similar application issues in the future, could you please post them to the upstream project. Always provide the logs (as you just did) and indicate which docker image you are using. 

Thanks.
